### ISSUE TITLE
`tape version` should return current version of binary in use

### ISSUE THREAD

**Issue by guoger** [guoger/tape#113]
`tape version` should return current version of binary in use

**Comment by PeerFintech** [comment]
The `version` is set by a const varable, which is changed manually when tape is released. `tape version' will print the version info at the control terminal and then the program will exit.
Is my understanding accurate? If so, I can fix the issue.

**Comment by hellosmallstone** [comment]
The version is set by a const varable, which is changed manually when tape is released. tape version will print the version info at the control terminal and then the program will exit.
Is my understanding accurate? If so, I can fix the issue.

**Comment by guoger** [comment]
@hellosmallstone thx for your interests in tackling this 👍 

Yes, your understanding is correct. And i have some suggestions wrt implementation.

roughly, we need to:
- introduce a proper cmd framework into `tape`, i.e. [cobra](https://github.com/spf13/cobra) (but i'm hoping for something more lightweight)
- introduce subcommand `run`, which does the same thing as today
- introduce subcommand `version`, which displays the version
- introduce subcommand `help` to print a nice and pretty help message

but we could start with baby steps and implement exactly what you described, no more no less

**Comment by hellosmallstone** [comment]
@guoger I understand this task and will fix it as soon as possible.
For the cmd framework, [kingpin](https://github.com/alecthomas/kingpin) maybe a better choice, which is lightweight in my opinion. If you have no objection to this, I will use kingpin.

**Comment by guoger** [comment]
> @guoger I understand this task and will fix it as soon as possible.
> For the cmd framework, [kingpin](https://github.com/alecthomas/kingpin) maybe a better choice, which is lightweight in my opinion. If you have no objection to this, I will use kingpin.

Sounds good. Pls make incremental changes: introduce kingpin in one commit, add new subcommand in another

**Comment by guoger** [comment]
I believe this issue is not fixed yet (inadvertently auto-closed by #119 )

**Comment by hellosmallstone** [comment]
> 
> 
> I believe this issue is not fixed yet (inadvertently auto-closed by #119 )
> 
> @hellosmallstone you'll still be working on this, right?

@guoger  Yeah, I have added the second modification. Please review it.
