### ISSUE TITLE
connection retry

### ISSUE THREAD

**Issue by SamYuan1990** [guoger/tape#117]
### Is your proposal related to a problem?
Some time fails create connection between tape and peer.

### Describe the solution you'd like
add a general 3 times retry for connection creation before error.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by stone-ch** [comment]
Would connection retry cost more time?

**Comment by SamYuan1990** [comment]
> Would connection retry cost more time when calculate the tps?

no， just retry to set up connection.
Tape works as set up connection and send test data.
the calculation starts form data send.

**Comment by guoger** [comment]
this looks good to me

**Comment by SamYuan1990** [comment]
https://github.com/grpc/grpc-go/blob/02cd07d9bb5609fe76f8bb8d948037e79a8b29c7/examples/features/retry/README.md

https://github.com/hyperledger/fabric/blob/master/internal/pkg/comm/client.go#L178

for my understanding... it seems that fabric client code invokes grpc from it's vendor folder.
which is a/an old version of grpc code which doesn't support retry feature in latest grpc?

@guoger

**Comment by guoger** [comment]
- we could always retry at application layer, or
- we could always switch to latest grpc-go if necessary

**Comment by SamYuan1990** [comment]
ok, let's make it at application layer.
