### ISSUE TITLE
tape: error: unexpected config.yaml, try --help

### ISSUE THREAD

**Issue by yongmu-lol** [guoger/tape#129]
i want to test my fabric，and this error showed up，how can i  deal with that?

**Comment by yongmu-lol** [comment]
./tape  --config=config.yaml --number=40000  this is the command which can run the tape

**Comment by SamYuan1990** [comment]
I am confusing ... ref line here, with latest version tape:
https://dev.azure.com/guojiannan1101/Tape/_build/results?buildId=536&view=logs&j=289dde38-8af5-54ac-d144-4ee017fbf3de&t=70d84ac3-f037-59f6-8903-009731559175&l=885

```
 tape -c /config/test/config20org1andorg2.yaml -n 500
```

I hope you are able to follow bug report template and we can know what's happened. 
your config.yaml matches the dir with the -c parameter?
or you are using old version of tape?

**Comment by yongmu-lol** [comment]
I  want to figure out the performance of  my fabric network which  deployed my own chaincode,and i followed the doc which told me to run the command"./tape config.yaml 40000" to run the test.But i failed with the error :tape: error: unexpected config.yaml, try --help.Then i used ./tape --help to see what happened.And it shows "run* --config=CONFIG --number=NUMBER  Start the tape program".So i used the command"./tape  --config=config.yaml --number=40000" instead of the command"./tape config.yaml 40000".This time i can run the test but it still has error which repeatly shows"ERRO[0009] Err processing proposal: %!s(<nil>), status: 500, message: This vehicle already exists: 2, addr: localhost:9051",how can i deal with it?Thanks a lot！

**Comment by yongmu-lol** [comment]
I see.....the error is related to my chaincode...

**Comment by SamYuan1990** [comment]
> I see.....the error is related to my chaincode...

good luck

**Comment by yongmu-lol** [comment]
this is a good test tool for fabric,but if i can test the latency,i think it will be greater

**Comment by SamYuan1990** [comment]
> this is a good test tool for fabric,but if i can test the latency,i think it will be greater

welcome for code contribution as #94

**Comment by yongmu-lol** [comment]
excuse me，i have two questions:
1.The result shows a performance called duration,what does it mean?Can it represent the latency when i use duration/tx?

2.I can implement the performance of querying my  element in my chaincode.When it comes to another function i defined in my chaincode,it doesn't work.As i mentioned before,when i want to test the TPS of adding a element(in my chaincode is addVehicle),ERRO[0005] Err processing proposal: %!s(<nil>), status: 500, message: This vehicle already exists: 5, addr: localhost:7051.As far as i am  concerned,the command"./tape --config=config.yaml --number=40000 "has an interacion with chaincode,so when i turn to the chaincode for verifying.And the result verify my guess,the information of vehicle 5 exists when the first tx complete,so the next txs can not addVehicle 5,so the error shows up.How can i deal with it？

**Comment by SamYuan1990** [comment]
> excuse me，i have two questions:
> 1.The result shows a performance called duration,what does it mean?Can it represent the latency when i use duration/tx?
> 
> 2.I can implement the performance of querying my element in my chaincode.When it comes to another function i defined in my chaincode,it doesn't work.As i mentioned before,when i want to test the TPS of adding a element(in my chaincode is addVehicle),ERRO[0005] Err processing proposal: %!s(), status: 500, message: This vehicle already exists: 5, addr: localhost:7051.As far as i am concerned,the command"./tape --config=config.yaml --number=40000 "has an interacion with chaincode,so when i turn to the chaincode for verifying.And the result verify my guess,the information of vehicle 5 exists when the first tx complete,so the next txs can not addVehicle 5,so the error shows up.How can i deal with it？

pls read #94 carefully.
and see this, any type of performance testing like this:
```
while(time){
send something to server.
}
```
so in your `addVehicle 5`,  won't support a while loop testing, in my point of view, it is a general performance testing issue which not tape scope.

**AGAIN, PLEASE FOLLOW OUR ISSUE TEMPLATE, AS THE TEMPLATE HITS THAT SHOULD AVOID REPORTING ANY GENERAL PERFORMANCE TESTING ISSUE**
