### ISSUE TITLE
ProposalResponsePayloads from Peers do not match

### ISSUE THREAD

**Issue by gabrielzheng31** [guoger/tape#131]
**Describe the bug**
It works when calling a chaincode from the JS script, but fails in tape. The error is **ProposalResponsePayloads from Peers do not match**.

**Part of my config file**
It's strange that when I invoke some simple chaincode functions with short parameters, tape works normally. However it fails with follow parameters in complicated functions.
```
args:
  - base_tx
  - 04379014e00469b50713374741ff06a39e24c869d6e1855a684c159268ce67331a4af3ca09c4e74e7713e50aedc1d0533d1e3cdded042229d4d093b11bdd46b881
  - 1234

```

**Tape Logs**
INFO[0000] Start sending transactions.                  
DEBU[0000] Start sending broadcast                      
DEBU[0000] start observer                               
ERRO[0000] ProposalResponsePayloads from Peers do not match 

**Peer Logs**
dev-peer0.org2.example.com-fabcar_1-fb5bcc8bcbed61054a4b653d3984acf4ea372f2536012e48b6b793ad5a856732|2021-01-02T14:22:26.666Z info [c-api:lib/handler.js]                              **[mychannel-50608e54] Calling chaincode Invoke() succeeded. Sending COMPLETED message back to peer**  

peer0.org1.example.com|2021-01-02 14:22:26.666 UTC [endorser] callChaincode -> **INFO 0dc finished chaincode: fabcar duration: 14ms channel=mychannel txID=50608e54**

dev-peer0.org1.example.com-fabcar_1-fb5bcc8bcbed61054a4b653d3984acf4ea372f2536012e48b6b793ad5a856732|2021-01-02T14:22:26.666Z info [c-api:lib/handler.js]                              **[mychannel-50608e54] Calling chaincode Invoke() succeeded. Sending COMPLETED message back to peer**  

peer0.org1.example.com|2021-01-02 14:22:26.666 UTC [comm.grpc.server] 1 -> **INFO 0dd unary call completed grpc.service=protos.Endorser grpc.method=ProcessProposal grpc.peer_address=192.168.0.1:47232 grpc.code=OK grpc.call_duration=16.306043ms**

peer0.org2.example.com|2021-01-02 14:22:26.667 UTC [endorser] callChaincode -> **INFO 0ed finished chaincode: fabcar duration: 15ms channel=mychannel txID=50608e54**

peer0.org2.example.com|2021-01-02 14:22:26.667 UTC [comm.grpc.server] 1 -> **INFO 0ee unary call completed grpc.service=protos.Endorser grpc.method=ProcessProposal grpc.peer_address=192.168.0.1:35290 grpc.code=OK grpc.call_duration=17.141611ms**

peer0.org2.example.com|2021-01-02 14:22:26.669 UTC [comm.grpc.server] 1 -> **INFO 0ef streaming call completed grpc.service=protos.Deliver grpc.method=DeliverFiltered grpc.peer_address=192.168.0.1:35298 error="context finished before block retrieved: context canceled" grpc.code=Unknown grpc.call_duration=21.640987ms**

orderer.example.com|2021-01-02 14:22:26.669 UTC [orderer.common.broadcast] Handle -> **WARN 0b2 Error reading from 192.168.0.1:48902: rpc error: code = Canceled desc = context canceled**

orderer.example.com|2021-01-02 14:22:26.669 UTC [comm.grpc.server] 1 -> **INFO 0b3 streaming call completed grpc.service=orderer.AtomicBroadcast grpc.method=Broadcast grpc.peer_address=192.168.0.1:48902 error="rpc error: code = Canceled desc = context canceled" grpc.code=Canceled grpc.call_duration=25.158893ms**

**Additional context**

**Comment by SamYuan1990** [comment]
take a look at this: https://github.com/guoger/tape/blob/master/docs/configfile.md
if the fabcar is the fabcar from sample... could you please confirm args are correct?

general speaking, this error shows that the endorsement result from peers you given are mismatched.

**Comment by gabrielzheng31** [comment]
Thanks for replying. The "fabrcar" here is not the one from sample. I replace the original functions with my own ones. Here is the detailed situation.

|           |  func_A  | func_B |
|:---------:|:--------:|:------:|
| JS Script |   pass   |  pass  |
|    Tape   | **fail** |  pass  |

func_A and func_B both can be invoked from a JS script. However, only func_B can be tested by Tape, and func_A always comes along with the **ERRO[0000] ProposalResponsePayloads from Peers do not match**. It's strange that func_A can be invoked by a script but fails in Tape.

**Comment by SamYuan1990** [comment]
> Thanks for replying. The "fabrcar" here is not the one from sample. I replace the original functions with my own ones. Here is the detailed situation.
> 
> func_A	func_B
> JS Script	pass	pass
> Tape	**fail**	pass
> func_A and func_B both can be invoked from a JS script. However, only func_B can be tested by Tape, and func_A always comes along with the **ERRO[0000] ProposalResponsePayloads from Peers do not match**. It's strange that func_A can be invoked by a script but fails in Tape.

I suppose below ways will help us.
1. confirm your endorsement logic is Peer A and Peer B.
1. invoke func_A from CLI/any SDK to see if able to success.
1. adding a log msg with result before return from func_A.
1. invoke func_A from CLI/any SDK again and see the output(as the logging msg) from Peer A and Peer B.
I suppose the out put from A and B should be diff.
CC @guoger 

If the output from A and B are the same... em... I suppose we need to adding logging in Tape and ask your help for testing.

**Comment by gabrielzheng31** [comment]
Step2 succeed.

And I suppose outputs from Peer A and Peer B are the same.

Logging information locates in the second last row, which is "Log msg."

**Outputs from Peer A**
```
+ CHAINCODE_DIR=/usr/local/src
+ cd /usr/local/src
+ npm start -- --peer.address peer0.org1.example.com:7052

> reputation-contract-v2@0.0.1 start /usr/local/src
> fabric-chaincode-node start "--peer.address" "peer0.org1.example.com:7052"

2021-01-03T05:18:50.773Z info [c-api:contracts-spi/bootstrap.js]                  No metadata file supplied in contract, introspection will generate all the data  
2021-01-03T05:18:50.777Z info [c-api:./lib/contract.js]                           Creating new Contract  
2021-01-03T05:18:50.777Z info [c-api:./lib/contract.js]                           Creating new Contract "org.hyperledger.fabric" 
2021-01-03T05:18:50.814Z info [c-api:lib/chaincode.js]                            Registering with peer peer0.org1.example.com:7052 as chaincode "fabcar_1:d6edae53cff0d75ce394ba586aed0564fd911bd8d3c2db5aa678083a723264b0"  
2021-01-03T05:18:50.821Z info [c-api:fabric-shim/cli]                             
Command succeeded
  
2021-01-03T05:18:50.859Z info [c-api:lib/handler.js]                              Successfully registered with peer node. State transferred to "established"  
2021-01-03T05:18:50.860Z info [c-api:lib/handler.js]                              Successfully established communication with peer node. State transferred to "ready"  
Log msg.
2021-01-03T05:20:43.433Z info [c-api:lib/handler.js]                              [mychannel-338d06f0] Calling chaincode Invoke() succeeded. Sending COMPLETED message back to peer  
```

**Outputs from Peer B**
```
> reputation-contract-v2@0.0.1 start /usr/local/src
> fabric-chaincode-node start "--peer.address" "peer0.org2.example.com:9052"

2021-01-03T05:18:49.731Z info [c-api:contracts-spi/bootstrap.js]                  No metadata file supplied in contract, introspection will generate all the data  
2021-01-03T05:18:49.734Z info [c-api:./lib/contract.js]                           Creating new Contract  
2021-01-03T05:18:49.735Z info [c-api:./lib/contract.js]                           Creating new Contract "org.hyperledger.fabric" 
2021-01-03T05:18:49.771Z info [c-api:lib/chaincode.js]                            Registering with peer peer0.org2.example.com:9052 as chaincode "fabcar_1:d6edae53cff0d75ce394ba586aed0564fd911bd8d3c2db5aa678083a723264b0"  
2021-01-03T05:18:49.779Z info [c-api:fabric-shim/cli]                             
Command succeeded
  
2021-01-03T05:18:49.815Z info [c-api:lib/handler.js]                              Successfully registered with peer node. State transferred to "established"  
2021-01-03T05:18:49.817Z info [c-api:lib/handler.js]                              Successfully established communication with peer node. State transferred to "ready"  
Log msg.
2021-01-03T05:21:20.840Z info [c-api:lib/handler.js]                              [mychannel-7fdad127] Calling chaincode Invoke() succeeded. Sending COMPLETED message back to peer  
```

**Comment by SamYuan1990** [comment]
> Step2 succeed.
> 
> And I suppose outputs from Peer A and Peer B are the same.
> 
> Logging information locates in the second last row, which is "Log msg."
> 
> **Outputs from Peer A**
> 
> ```
> + CHAINCODE_DIR=/usr/local/src
> + cd /usr/local/src
> + npm start -- --peer.address peer0.org1.example.com:7052
> 
> > reputation-contract-v2@0.0.1 start /usr/local/src
> > fabric-chaincode-node start "--peer.address" "peer0.org1.example.com:7052"
> 
> 2021-01-03T05:18:50.773Z info [c-api:contracts-spi/bootstrap.js]                  No metadata file supplied in contract, introspection will generate all the data  
> 2021-01-03T05:18:50.777Z info [c-api:./lib/contract.js]                           Creating new Contract  
> 2021-01-03T05:18:50.777Z info [c-api:./lib/contract.js]                           Creating new Contract "org.hyperledger.fabric" 
> 2021-01-03T05:18:50.814Z info [c-api:lib/chaincode.js]                            Registering with peer peer0.org1.example.com:7052 as chaincode "fabcar_1:d6edae53cff0d75ce394ba586aed0564fd911bd8d3c2db5aa678083a723264b0"  
> 2021-01-03T05:18:50.821Z info [c-api:fabric-shim/cli]                             
> Command succeeded
>   
> 2021-01-03T05:18:50.859Z info [c-api:lib/handler.js]                              Successfully registered with peer node. State transferred to "established"  
> 2021-01-03T05:18:50.860Z info [c-api:lib/handler.js]                              Successfully established communication with peer node. State transferred to "ready"  
> Log msg.
> 2021-01-03T05:20:43.433Z info [c-api:lib/handler.js]                              [mychannel-338d06f0] Calling chaincode Invoke() succeeded. Sending COMPLETED message back to peer  
> ```
> 
> **Outputs from Peer B**
> 
> ```
> > reputation-contract-v2@0.0.1 start /usr/local/src
> > fabric-chaincode-node start "--peer.address" "peer0.org2.example.com:9052"
> 
> 2021-01-03T05:18:49.731Z info [c-api:contracts-spi/bootstrap.js]                  No metadata file supplied in contract, introspection will generate all the data  
> 2021-01-03T05:18:49.734Z info [c-api:./lib/contract.js]                           Creating new Contract  
> 2021-01-03T05:18:49.735Z info [c-api:./lib/contract.js]                           Creating new Contract "org.hyperledger.fabric" 
> 2021-01-03T05:18:49.771Z info [c-api:lib/chaincode.js]                            Registering with peer peer0.org2.example.com:9052 as chaincode "fabcar_1:d6edae53cff0d75ce394ba586aed0564fd911bd8d3c2db5aa678083a723264b0"  
> 2021-01-03T05:18:49.779Z info [c-api:fabric-shim/cli]                             
> Command succeeded
>   
> 2021-01-03T05:18:49.815Z info [c-api:lib/handler.js]                              Successfully registered with peer node. State transferred to "established"  
> 2021-01-03T05:18:49.817Z info [c-api:lib/handler.js]                              Successfully established communication with peer node. State transferred to "ready"  
> Log msg.
> 2021-01-03T05:21:20.840Z info [c-api:lib/handler.js]                              [mychannel-7fdad127] Calling chaincode Invoke() succeeded. Sending COMPLETED message back to peer  
> ```

Sorry? where is the output from A and B before return?

**Comment by gabrielzheng31** [comment]
It appears I misunderstand you and I might figure out what the problem is. **My func_A always return different values**. Is that the reason why it failed when invoking by Tape?

**Comment by gabrielzheng31** [comment]
**Outputs from Peer A**
```
2021-01-03T05:43:03.319Z info [c-api:lib/handler.js]                              Successfully registered with peer node. State transferred to "established"  
2021-01-03T05:43:03.320Z info [c-api:lib/handler.js]                              Successfully established communication with peer node. State transferred to "ready"  
{
  base_tx_hash: '53b15caa6dc4a6b732a781cf6eb38faa870607bee6f3bccdb76f32e75317808f',
  Ko: '043a0a362c0ea0860cb59165fdff6a38ca159b1150898846c25380b0e5c745eeea7b54810df5e3786de09f9a5b86ab15c023d0c8eac92120f80c1e470e02df5530',
  amount: '1234',
  commitment: '041362b3e12a459fec715ea3fe41bbb089fdb18649302ef0e455edb79378cd70dc1b566132921da0b91e2a4a00cffd63524522431364239d2f07e45961b75934f1',
  R: '0429839185aa2aaa7480398e1ef4ea64561435c3e3672522530cc2ef1a35ef70b04b766d903a6ec7e1870d17f426921d3e90e8ecf4b046d92625acb9a6a4e78344'
}
2021-01-03T05:44:09.579Z info [c-api:lib/handler.js]                              [mychannel-796b5e20] Calling chaincode Invoke() succeeded. Sending COMPLETED message back to peer  
```

**Outputs from Peer B**
```
2021-01-03T05:43:03.300Z info [c-api:lib/handler.js]                              Successfully registered with peer node. State transferred to "established"  
2021-01-03T05:43:03.301Z info [c-api:lib/handler.js]                              Successfully established communication with peer node. State transferred to "ready"  
{
  base_tx_hash: '2aa6d1b1ed1eb29d2d824e3095168dac262c8081a7197a4866c2b9609fbdda59',
  Ko: '0458238bc963cef151ba23f9c73753b819f667dbd1e8a80d7e69fe9d44572a46f73cc3356b30ff68e8aa34935d19ac3cf20794f1509b9c1df516d47539e05e9190',
  amount: '1234',
  commitment: '041362b3e12a459fec715ea3fe41bbb089fdb18649302ef0e455edb79378cd70dc1b566132921da0b91e2a4a00cffd63524522431364239d2f07e45961b75934f1',
  R: '040c5b24b5455a508f5f47a18b5bc5e34d164b714cdde748f5c057c9aa946fda9c3e4f1ba4676d503df9791c043042a2bf2c0ef63e79b91deedf09aaab8de20b9e'
}
2021-01-03T05:44:04.630Z info [c-api:lib/handler.js]                              [mychannel-df05eea9] Calling chaincode Invoke() succeeded. Sending COMPLETED message back to peer  
```

**However, tape fails again when I only return 'ok'. It's confusing.**
**Here are the last few lines of my code. (Fails either)**
```
const buffer = Buffer.from(JSON.stringify(asset));
await ctx.stub.putState(tx_hash, buffer);
console.log(asset)
// return asset;
return 'ok';
```

**Comment by SamYuan1990** [comment]
> **Outputs from Peer A**
> 
> ```
> 2021-01-03T05:43:03.319Z info [c-api:lib/handler.js]                              Successfully registered with peer node. State transferred to "established"  
> 2021-01-03T05:43:03.320Z info [c-api:lib/handler.js]                              Successfully established communication with peer node. State transferred to "ready"  
> {
>   base_tx_hash: '53b15caa6dc4a6b732a781cf6eb38faa870607bee6f3bccdb76f32e75317808f',
>   Ko: '043a0a362c0ea0860cb59165fdff6a38ca159b1150898846c25380b0e5c745eeea7b54810df5e3786de09f9a5b86ab15c023d0c8eac92120f80c1e470e02df5530',
>   amount: '1234',
>   commitment: '041362b3e12a459fec715ea3fe41bbb089fdb18649302ef0e455edb79378cd70dc1b566132921da0b91e2a4a00cffd63524522431364239d2f07e45961b75934f1',
>   R: '0429839185aa2aaa7480398e1ef4ea64561435c3e3672522530cc2ef1a35ef70b04b766d903a6ec7e1870d17f426921d3e90e8ecf4b046d92625acb9a6a4e78344'
> }
> 2021-01-03T05:44:09.579Z info [c-api:lib/handler.js]                              [mychannel-796b5e20] Calling chaincode Invoke() succeeded. Sending COMPLETED message back to peer  
> ```
> 
> **Outputs from Peer B**
> 
> ```
> 2021-01-03T05:43:03.300Z info [c-api:lib/handler.js]                              Successfully registered with peer node. State transferred to "established"  
> 2021-01-03T05:43:03.301Z info [c-api:lib/handler.js]                              Successfully established communication with peer node. State transferred to "ready"  
> {
>   base_tx_hash: '2aa6d1b1ed1eb29d2d824e3095168dac262c8081a7197a4866c2b9609fbdda59',
>   Ko: '0458238bc963cef151ba23f9c73753b819f667dbd1e8a80d7e69fe9d44572a46f73cc3356b30ff68e8aa34935d19ac3cf20794f1509b9c1df516d47539e05e9190',
>   amount: '1234',
>   commitment: '041362b3e12a459fec715ea3fe41bbb089fdb18649302ef0e455edb79378cd70dc1b566132921da0b91e2a4a00cffd63524522431364239d2f07e45961b75934f1',
>   R: '040c5b24b5455a508f5f47a18b5bc5e34d164b714cdde748f5c057c9aa946fda9c3e4f1ba4676d503df9791c043042a2bf2c0ef63e79b91deedf09aaab8de20b9e'
> }
> 2021-01-03T05:44:04.630Z info [c-api:lib/handler.js]                              [mychannel-df05eea9] Calling chaincode Invoke() succeeded. Sending COMPLETED message back to peer  
> ```
> 
> **However, tape fails again when I only return 'ok'. It's confusing.**
> **Here are the last few lines of my code. (Fails either)**
> 
> ```
> const buffer = Buffer.from(JSON.stringify(asset));
> await ctx.stub.putState(tx_hash, buffer);
> console.log(asset)
> // return asset;
> return 'ok';
> ```

try
```
//const buffer = Buffer.from(JSON.stringify(asset));
//await ctx.stub.putState(tx_hash, buffer);
//console.log(asset)
// return asset;
return 'ok';
```

ref here https://github.com/guoger/tape/blob/master/test/config20selectendorser.yaml#L27 in our CI.

yep, your chaincode returns different value each time.
as
https://github.com/guoger/tape/blob/2b0043eb65c752cc44ca606baf2ddc55fd882e8a/pkg/infra/proposal.go#L106
it compares bytes.

**Comment by gabrielzheng31** [comment]
I sumbit a predefined asset to the system while keeping the rest of the code unchanged. It finally works. I'm grateful that you spend time helping me in your holidays. Thank you very much.

**Comment by haojunsheng** [comment]
也有可能是invoke的时候发送的交易量过大，导致peer节点报错。如下所示：
![image](https://user-images.githubusercontent.com/12840295/111982782-58df5380-8b44-11eb-8abb-aeba308ca279.png)
