### ISSUE TITLE
Adding precheck if chaincode not exsit.

### ISSUE THREAD

**Issue by SamYuan1990** [guoger/tape#52]
to avoid 
```
time="2020-08-01T05:39:43Z" level=error msg="Err processing proposal: %!s(<nil>), status: 500, addr: localhost:9051 \n"
```

**Comment by guoger** [comment]
In order to fail early, we could send **one** scout Tx and see it passing through Fabric successfully, before producing heavy traffic.

Although i don't think we should check specific errors (there could be way too many possibilities to check), at least for now.
