### ISSUE TITLE
Launch with connection issue

### ISSUE THREAD

**Issue by malajisi** [guoger/tape#83]
## Environments:
- OS: Ubuntu 18
- Go: 1.15.3

## /etc/hosts
```
127.0.0.1       peer0.org1.example.com
127.0.0.1       peer0.org2.example.com
127.0.0.1       orderer.example.com
127.0.0.1       peer1
127.0.0.1       peer2
127.0.0.1       orderer1
```

**Comment by SamYuan1990** [comment]
> ## ERRO[0000] error connecting to localhost:7051: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:7051: connect: connection refused"#
> ## Environments:
> * OS: Ubuntu 18
> * Go: 1.15.3
> 
> ## /etc/hosts
> ```
> 127.0.0.1       peer0.org1.example.com
> 127.0.0.1       peer0.org2.example.com
> 127.0.0.1       orderer.example.com
> 127.0.0.1       peer1
> 127.0.0.1       peer2
> 127.0.0.1       orderer1
> ```

1) please check your peer log.
2) please check your port 7051.

if there any further issue, please upload log and your steps in this issue for reproduce.

**Comment by malajisi** [comment]
Thanks, it's a my config file problem.
