### ISSUE TITLE
my private key does not match public key,please help me

### ISSUE THREAD

**Issue by nthmnqy** [guoger/tape#85]
My config.yaml is written like this

> private_key: /home/niqinyin/go/src/github.com/kongyixueyuan.com/education/fixtures/crypto-config/peerOrganizations/org1.kevin.kongyixueyuan.com/users/Admin@org1.kevin.kongyixueyuan.com/msp/keystore/c24c159c6de601f2703c4e4273682b08cda54ebdaf4ca1c4aa4b3f80b8a91964_sk

I've tried the user's private key, too.But it always reported such an error

> ERRO[0000] error connecting to localhost:7051: failed to load client certificate: tls: private key does not match public key 

please help me

**Comment by SamYuan1990** [comment]
> My config.yaml is written like this
> 
> > private_key: /home/niqinyin/go/src/github.com/kongyixueyuan.com/education/fixtures/crypto-config/peerOrganizations/org1.kevin.kongyixueyuan.com/users/Admin@org1.kevin.kongyixueyuan.com/msp/keystore/c24c159c6de601f2703c4e4273682b08cda54ebdaf4ca1c4aa4b3f80b8a91964_sk
> 
> I've tried the user's private key, too.But it always reported such an error
> 
> > ERRO[0000] error connecting to localhost:7051: failed to load client certificate: tls: private key does not match public key
> 
> please help me

ref here for how we config key with fabric sample
https://github.com/guoger/tape/blob/master/test/config20org1andorg2.yaml
and here for CI....
https://dev.azure.com/guojiannan1101/guojiannan1101/_build/results?buildId=412&view=logs&j=e17a8fb5-2251-55b7-e47c-128cd85495af&t=0ddee50c-f18c-55ff-c001-5d076dda0c84&l=1

Honestly  speaking, key mismatch is out of tape scope.

**Comment by nthmnqy** [comment]
@SamYuan1990 Thank you for your help. But when I write config.yaml, I don't know how to write args. My function name is "addfile",the type of its parameter is []String ,its parameter is [{"FileName":"1.txt","ID":"121","IPAdress":"1.1.1.2","OrgName":"org2","ModifyTime":"8:27 2019/9/12"}，eventAddFile], how should I write the args

**Comment by SamYuan1990** [comment]
> @SamYuan1990 Thank you for your help. But when I write config.yaml, I don't know how to write args. My function name is "addfile",the type of its parameter is []String ,its parameter is [{"FileName":"1.txt","ID":"121","IPAdress":"1.1.1.2","OrgName":"org2","ModifyTime":"8:27 2019/9/12"}，eventAddFile], how should I write the args

https://github.com/guoger/tape/blob/master/test/config14org1andorg2.yaml#L27-L29

**Comment by SamYuan1990** [comment]
https://github.com/guoger/tape/blob/master/docs/configfile.md

**Comment by SamYuan1990** [comment]
don't duplicate issue with https://github.com/guoger/tape/issues/86

**Comment by qii67** [comment]
> My config.yaml is written like this
> 
> > private_key: /home/niqinyin/go/src/github.com/kongyixueyuan.com/education/fixtures/crypto-config/peerOrganizations/org1.kevin.kongyixueyuan.com/users/Admin@org1.kevin.kongyixueyuan.com/msp/keystore/c24c159c6de601f2703c4e4273682b08cda54ebdaf4ca1c4aa4b3f80b8a91964_sk
> 
> I've tried the user's private key, too.But it always reported such an error
> 
> > ERRO[0000] error connecting to localhost:7051: failed to load client certificate: tls: private key does not match public key
> 
> please help me

I'm facing the same problem, can you tell me how you solve the problem "private key does not match public key"?
the config.yaml is just like:
`mspid: Org1MSP
private_key: /config/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/029e6f199d81a1de05811bcadd60a0ab0ac117198ce0d4d05ef859d2f568bcfd_sk
sign_cert: /config/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
`

**Comment by xuan-cmd** [comment]
> My config.yaml is written like this
> 
> > private_key: /home/niqinyin/go/src/github.com/kongyixueyuan.com/education/fixtures/crypto-config/peerOrganizations/org1.kevin.kongyixueyuan.com/users/[Admin@org1.kevin.kongyixueyuan.com](mailto:Admin@org1.kevin.kongyixueyuan.com)/msp/keystore/c24c159c6de601f2703c4e4273682b08cda54ebdaf4ca1c4aa4b3f80b8a91964_sk
> 
> I've tried the user's private key, too.But it always reported such an error
> 
> > ERRO[0000] error connecting to localhost:7051: failed to load client certificate: tls: private key does not match public key
> 
> please help me

Can I ask you how you solved it? Please, I need your help.

**Comment by xuan-cmd** [comment]
I checked my configuration, but didn't see where the problem was.

**Comment by SamYuan1990** [comment]
In most case, TLS configuration is owned by user. Just point out how to configuration for Tape as usage guide.
As for Tape maintainer can't touch user's network or key settings.
