### ISSUE TITLE
how to write the "args" in config.yaml

### ISSUE THREAD

**Issue by nthmnqy** [guoger/tape#86]
When I write config.yaml, I don't know how to write args. 
My function name is "addfile",the type of its parameter is []String ,its parameter is [{"FileName":"1.txt","ID":"121","IPAdress":"1.1.1.2","OrgName":"org2","ModifyTime":"8:27 2019/9/12"}，"eventAddFile"], how should I write the args?
By the way, when calling chain code from the Ubuntu command line, the common command is written like this
`peer chaincode invoke --tls --cafile $ORDERER_CA -C mychannel -n mycc -c '{"Args":["get","a"]}'`
So how do my functions write commands

**Comment by SamYuan1990** [comment]
https://github.com/guoger/tape/blob/master/test/config14org1andorg2.yaml#L27-L29

**Comment by SamYuan1990** [comment]
https://github.com/guoger/tape/blob/master/docs/configfile.md

**Comment by SamYuan1990** [comment]
pls check readme and samples carefully.
