### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by SamYuan1990** [guoger/tape#92]
# Bug:
Hint: Let's decouple Tape bug with general issues as TLS cert config error,general performance testing issue as resource been eat up, or fabric bugs.
Hint: For any platform specific issues, please try to reproduce by Mac/Linux. For ex, it's hard for Tape maintainers to investigating issue on any kind of IOT device as we don't have your device. 
## How to reproduce via test-network or minifab:

# Feature:
## Scenario: 
if tape supports this feature, then tape user able to benefits
## Scenario: 
if tape supports this feature, then tape user able to benefits
### any current workaround:
...

**Comment by stone-ch** [comment]
We have added a bug issue template here https://github.com/guoger/tape/pull/98
